version: 2
jobs:
  build:
    docker:
      - image: suginamiku/le3sw:latest
    steps:
      - checkout
      - run:
          name: Build
          command: |
            eval $(opam env)
            cd minimlInterp && dune build
      - run:
          name: Test
          command: |
            eval $(opam env)
            cd minimlInterp && dune runtest
